### ISSUE TITLE
payment status not verified?

### ISSUE THREAD

**Issue by danmarsden** [eLearning-BS23/moodle-paygw_cardinity#4]
in the process page, shouldn't the payment status be verified? - eg status = "approved" before allowing the user entry to the course? - doesn't cardinity allow other statuses like "pending" or "declined" to be returned here?

https://github.com/eLearning-BS23/moodle-paygw_cardinity/blob/main/process.php#L66

**Comment by danmarsden** [comment]
also - typically rather than "recieving" the full information via a post and trusting it, a payment processing plugin will usually make an external call to the Payment processing api - asking the external api "what information do you have on this transaction" - then check the response for that transaction directly from an api call - making sure that the transaction exists and the user has paid.

**Comment by nawazsharif** [comment]
Issue fixed
